### ISSUE TITLE
Refresh access token when it expires

### ISSUE THREAD

**Issue by raws** [raws/alfred-imgur#2]
Imgur access tokens [expire after one hour](https://api.imgur.com/oauth2#overview). The workflow stores a `refresh_token` in its settings, which can be used to [acquire a new access token](https://api.imgur.com/oauth2#refresh_tokens) without asking the user to authenticate the app again.

The Imgur API documentation isn't very clear on what kind of response is returned when the access token you try to use has expired. That will take some discovery.

**Comment by Reeywhaar** [comment]
Have similar but error is "The access token provided is invalid."

**Comment by raws** [comment]
Hmm, I think I've noticed that as well. I'll see if I can figure out what's up.

**Comment by Reeywhaar** [comment]
Oh, nevermind. I just clarified this in case someone google "imgur token expired" because it's the second link.

**Comment by raws** [comment]
Oh, hah, thanks. Weirdly though, I have been noticing that my access tokens seem to be expiring very quickly, which I still need to look into.
